# Development / integration testing only
version: '3.0'

services:
  bot:
    image: node:lts-slim@sha256:67ac68a9452c8e174d508babe0e99e0580a6c73ba8b1998cf2b5c80cdda38217
    volumes:
      - './:/src/bot'
    working_dir: /src/bot
    command: npm run nodemon
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin@sha256:9a7dbc81516a15348a250225fb79cd60d0d9938f1a5373b2a0118ba8c828ffdf
