# Development / integration testing only
version: '3.0'

services:
  bot:
    image: node:lts-slim@sha256:e5936cf8dbbb3c0d9d337c0e9f23e56e00b7e62280a8a617d12adfdda8ca9f11
    volumes:
      - './:/src/bot'
    working_dir: /src/bot
    command: npm run nodemon
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin@sha256:b3435e485f1e73266dba48ae56814c6731ffb76563a0b809456876f29a575f6b
