# Development / integration testing only
version: '3.0'

services:
  bot:
    image: node:lts-slim@sha256:f8cb96358ff1d2264e0e70f1dc35537735876c02fd6d8f568eec681a9b991bde
    volumes:
      - './:/src/bot'
    working_dir: /src/bot
    command: npm run nodemon
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin@sha256:b3435e485f1e73266dba48ae56814c6731ffb76563a0b809456876f29a575f6b
