# Development / integration testing only
version: '3.0'

services:
  bot:
    image: node:lts-slim@sha256:9b43cdacd070d1b38976a804aec78f03139c600865a3c72501af3bbec8d4bdee
    volumes:
      - './:/src/bot'
    working_dir: /src/bot
    command: npm run nodemon
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin@sha256:b3435e485f1e73266dba48ae56814c6731ffb76563a0b809456876f29a575f6b
