# Development / integration testing only
version: '3.0'

services:
  bot:
    image: node:lts-slim@sha256:bd728768518439b05d355f58518a01b31a15f58381592e3ffa78e7939889f4f1
    volumes:
      - './:/src/bot'
    working_dir: /src/bot
    command: npm run nodemon
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin@sha256:9a7dbc81516a15348a250225fb79cd60d0d9938f1a5373b2a0118ba8c828ffdf
