# Development / integration testing only
version: '3.0'

services:
  bot:
    image: node:lts-slim@sha256:472d9627d088c880e27e0070a836108b1ae1f4d81488892cc7128fa41ebe4b4c
    volumes:
      - './:/src/bot'
    working_dir: /src/bot
    command: npm run nodemon
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin@sha256:947ca34f00cef4a4732042dff489fd7c2e5a7867c70ade1b836b7d20aad9bf68
