# Development / integration testing only

version: '3.0'

services:
  bot:
    image: node:lts-alpine
    volumes: 
      - './:/src/bot'
    working_dir: /src/bot
    command: npm run nodemon
    env_file:
      - .env
