apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-tgbots
  namespace: bots
spec:
  secretName: certificate-prod-tgbots
  dnsNames:
    - tgbots.myrotvorets.center
  issuerRef:
    name: clusterissuer-le-myrotvorets
    kind: ClusterIssuer
