apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-le-myrotvorets
  namespace: bots
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@myrotvorets.center
    privateKeySecretRef:
      name: letsencrypt-prod-myrotvorets
    solvers:
      - selector:
          dnsZones:
            - myrotvorets.center
            - "*.myrotvorets.center"
        dns01:
          cloudflare:
            email: oxana@informnapalm.org
            apiTokenSecretRef:
              name: cloudflare-api-token-secret-oxana
              key: api-token
