apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bots

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - env: ".env"
    name: myrnews-bot-secret
    type: Opaque

resources:
  - "namespace.yaml"
  - "configmap.yaml"
  - "deployment.yaml"
  - "service.yaml"
  - "clusterissuer.yaml"
  - "certificate.yaml"
  - "ingress.yaml"
