name: Build and Test

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - '**:**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14']

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Check if Git tag exists
        run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
        if: startsWith(github.ref, 'refs/heads/')

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        if: startsWith(github.ref, 'refs/heads/') && !env.HEAD_TAG
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci --ignore-scripts
        if: startsWith(github.ref, 'refs/heads/') && !env.HEAD_TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run postinstall scripts
        if: startsWith(github.ref, 'refs/heads/') && !env.HEAD_TAG
        run: npm rebuild && npm run prepare --if-present

      - name: Run tests
        if: startsWith(github.ref, 'refs/heads/') && !env.HEAD_TAG
        run: npm test

      - name: Trigger Docker build
        if: startsWith(github.ref, 'refs/heads/') && !env.HEAD_TAG
        uses: myrotvorets/trigger-repository-dispatch-action@1.0.1
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          type: tests-passed
          payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "event_name": "${{ github.event_name }}" }'
